language: python
python:
  - 2.7
  - 3.4
notifications:
  email:
    on_success: change
    on_failure: always
# whitelist
branches:
  only:
    - master
sudo: false

# Setup anaconda
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda/bin:$PATH
  - export PATH=/home/travis/miniconda2/bin:$PATH
  - conda update --yes conda
# Install packages
install:
  - conda install --yes python=$TRAVIS_PYTHON_VERSION numpy scipy matplotlib nose seaborn numba
  - conda install -y -c https://conda.binstar.org/bashtage arch
  # - pip install git+https://github.com/bashtage/arch.git
  # - python setup.py build

# Run test
script:
  - python setup.py build
  - nosetests

# Calculate coverage
after_success:
  - coveralls --config_file .coveragerc